# Generated by Django 2.2.16 on 2020-10-26 14:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('TEXT', 'Plain text'), ('CODE', 'Source code')], default='CODE', max_length=2)),
                ('length', models.IntegerField()),
                ('difficulty', models.IntegerField()),
                ('likers', models.ManyToManyField(related_name='liked_source', to=settings.AUTH_USER_MODEL)),
                ('subscribers', models.ManyToManyField(related_name='subscribed_source', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(to='games.Tag')),
            ],
        ),
    ]
