# Generated by Django 2.2.16 on 2020-10-26 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20201026_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='content',
            field=models.TextField(default='Hello, world!'),
            preserve_default=False,
        ),
    ]
