# Generated by Django 2.2.16 on 2020-10-27 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_ban',
            field=models.BooleanField(default=False),
        ),
    ]
